### ISSUE TITLE
What's wrong with this

### ISSUE THREAD

**Issue by fern-leigh-zz** [Jadelette/Katas#5]
Hello, 

Please can you tell me where I'm going wrong with this: 

int totalBooksLeft = (v1Copies + v2Copies + v3Copies + v4Copies + v5Copies);

        System.out.println(totalBooksLeft);

        ArrayList<Integer> sets = new ArrayList<Integer>();

        ArrayList<Integer> booksByCopy = new ArrayList<Integer>();
        booksByCopy.add(v1Copies);
        booksByCopy.add(v2Copies);
        booksByCopy.add(v3Copies);
        booksByCopy.add(v4Copies);
        booksByCopy.add(v5Copies);

        int set = 0;

        while (totalBooksLeft >0) {

            //for (int volumeCopies : booksByCopy) {
            for (int i = 0; booksByCopy.get(i) > 0; i++){
                if (booksByCopy.get(i) > 0) {
                    set ++;
                    int newValue = booksByCopy.get(i) -1;
                    booksByCopy.add(i, newValue);
                    totalBooksLeft -=1;

                }
                sets.add(set);
                System.out.println(set);
                set = 0;

            }

            for (int setList : sets) {
                System.out.println(setList);

The idea is that: 
- while there are books in the basket (i.e. totalBooksLeft) > 0
- the for loop will go through each item in the array list booksByCopy
- this list contains a integer representing the amount of each volume in the basket
- for each volume, it should check if there are more than 0 of that volume in the basket
- if there are, it should increment the integer called 'set' by one
- if should decrease the amount of that volume by 1 and replace the value at the same index number with the reduced number
- then it should also reduce the amount of total books in the basket by 1. 

After looping through each item in the list (i.e. once through each possible volume), the integer 'set' should show whether a full or partial set of the five volumes can be created. (e.g. if set = 5, then there was at least one book of each volume in the basket; if set = 3, three different volumes were in the basket, but two had 0 copies in the basket - etc).

The number stored in the variable set should then be added to the array list called sets (e.g. 5 would be added if all books had more than one volume in the basket). the int 'set' would then be reset to 0. 

If the total number of books is still more than 0, the loop would run through each volume again. Another int representing a complete or partial set would be added to the sets array. 

When totalBooksLeft (in basket) reaches 0, the loop should stop running, and I should have an array list showing me how many full and partial sets of books can be made. 

All good in theory... but all it does is print out 1,1,1,1,1,1,1,1,1,1,1... ad infinitum. :'( 

Please can you tell me: 
a) does my logic makes sense / is what I'm trying to do achievable
b) where have I gone wrong? 

I've tried a bunch of different stuff, but I just can't get it to work! 

Thanks for your help! 

J

**Comment by fern-leigh-zz** [comment]
I updated it a bit, but it's still not working. (Thought I had it when I woke up).

here's how it looks now: 

 int totalBooksLeft = (v1Copies + v2Copies + v3Copies + v4Copies + v5Copies);

        System.out.println(totalBooksLeft);

        ArrayList<Integer> sets = new ArrayList<Integer>();

        ArrayList<Integer> booksByCopy = new ArrayList<Integer>();
        booksByCopy.add(v1Copies);
        booksByCopy.add(v2Copies);
        booksByCopy.add(v3Copies);
        booksByCopy.add(v4Copies);
        booksByCopy.add(v5Copies);

        int set = 0;

        while (totalBooksLeft >0) {

            //for (int volumeCopies : booksByCopy) {
            for (int i = 0; i <= booksByCopy.size(); i++){
                if (booksByCopy.get(i) > 0) {
                    set ++;
                    int newValue = booksByCopy.get(i) --;
                    booksByCopy.add(i, newValue);
                    totalBooksLeft --;

                }

                sets.add(set);
                System.out.println(set);
                set = 0;
            }


            for (int setList : sets) {
                System.out.println(setList);

            }

**Comment by timpharo** [comment]
Ok, so i have had a quick look and on line https://github.com/Jadelette/Katas/blob/d3e1c5a61fd60203399a96a95b02682110374ba0/src/main/potter/Potter.java#L155 you are resetting set to 0 for every loop.  This will always print 1 in your case as the first test provides 2 of the same copy, you increase set to 1, add it to sets and then reset set to 0.  You are also editing the variable that you are looping over which should be avoided as you are therefore looping over something that is ever changing   

**Back to your original questions:**
_a) does my logic makes sense / is what I'm trying to do achievable_
Yes, your logic does make sense and should be achievable, but there are other ways of tackling this with and without tdd.  For example my initial thought without digging to deep into it would be to use a HashMap instead of an ArrayList, where the key is the book title and the value is the copies.  We can have a look a bit more into this next time and ill try and give you an example.
 
_b) where have I gone wrong?_  
As mentioned above in the first test situation `set` can only ever be 1, so you will only be printing 1

Here is a quick attempt that would also have the advantage that it wouldn't matter what order the books are entered in:

`Map<String, Integer> bookCopies = new HashMap<>();

        for(String bookTitle : itemsInBasket) {
            Integer copies = bookCopies.get(bookTitle);

            /*
                This could be replaced if we called bookCopies.getOrDefault(bookTitle, 0); above instead
                of calling bookCopies.get(bookTitle)
            */
            if(copies == null){
                copies = 0;
            }

            copies ++;

            bookCopies.put(bookTitle, copies);
        }

        System.out.println(bookCopies);

        if(bookCopies.containsKey("Volume 1") &&
                bookCopies.containsKey("Volume 2") &&
                bookCopies.containsKey("Volume 3") &&
                bookCopies.containsKey("Volume 4") &&
                bookCopies.containsKey("Volume 5")) {
            System.out.println("The basket contains all volumes of the book");
        } else {
            System.out.println("The basket doesnt volumes of the book");
        }`

**Comment by timpharo** [comment]
Ok, so ignore the previous comment.  When i debugged the process i realised that because you were editing the same list that you were looping over, even though you were doing it by index you still shouldn't do this as it has funky side effects.  Can speak more about it next time but for now if you change the following line the test passes:

* Remove `booksByCopy.add(i, newValue);`
* Change ` int newValue = booksByCopy.get(i)` --; to  `int newValue = booksByCopy.get(i) -1;` if you 
* Change `for (int i = 0; i <= booksByCopy.size(); i++)` to `for (int i = 0; i < booksByCopy.size(); i++)`

Let me know how it goes :)

**Comment by fern-leigh-zz** [comment]
Hey - it a,most works, but I really need it to change the value, so that the next time round the books that have been counted are removed. 

Without doing this, it tells me there are four set of five books - which is totally wrong, as there is actually one set of five and one set of three. 

It's progress though - I'll see if I can figure out a way forward from here! :)

**Comment by fern-leigh-zz** [comment]
I've cracked it!
As predicted - I was overcomplicating things. The array and for loop were totally unnecessary, a I've already worked out the copies of each volume in the basket.. 

..All I needed was a bunch of simple 'if's: 

 while (totalBooksLeft >0) {

            if (v1Copies > 0) {
                set++;
                v1Copies--;
                totalBooksLeft--;
            }

            if (v2Copies >0) {
                set++;
                v2Copies--;
                totalBooksLeft--;
            }

            if (v3Copies >0) {
                set++;
                v3Copies--;
                totalBooksLeft--;
            }

            if (v4Copies >0) {
                set++;
                v4Copies--;
                totalBooksLeft--;
            }

            if (v5Copies >0) {
                set++;
                v5Copies--;
                totalBooksLeft--;
            }

            sets.add(set);
            System.out.println(set);
            set = 0;

Finally, it calculates how many sets of different books there are and whether the sets are complete (i.e. 5 books) or incomplete (i.e. 3 different books)! :) 

Now I just need to figure out how to make it calculate the best pricing combo and add the relevant discounts. Reckon I've got this though - so should have a fully working programme by next week's session!  :D

**Comment by fern-leigh-zz** [comment]
It works!! :D 

Like... the whole thing, I mean. It all works!

**Comment by Jadelette** [comment]
Argh - I changed it to use a hashmap, thinking it would be neater - but now if someone adds 3 copies of volume 1, then adds another one copy of volume 1 - it overwrites the original number of copies instead of adding them together (I get why - it's just really annoying!). I had it working fine with the list and broke it by trying to make it better! :'( 

At least all the calculation stuff still works... just got to rewrite my scannery bit. *sigh* 

I will actually finish this one day!

**Comment by timpharo** [comment]
If you look at my suggested solution it looped through all the books that came in, got the count from the hashmap(or 0 if the volume wasnt already there), added one to that count and then added it back to the hashmap.

TBH overall i think you are moving in bounds when it comes to flow control and putting you ideas into code. You should be proud of what you have achieved so far and next week we can always have a 'what the heck is this' session :+1:
